export const ALL_DAPP = [
  [
    {
      id: "1.1",
      name: "Finder",
      logo: "/application/Finder.png",
      position: {
        x: 0,
        y: 0,
        width: 1,
        height: 1,
      },
      page: 1,
    },
    {
      id: "1.2",
      name: "Finder",
      logo: "/application/Finder.png",
      position: {
        x: 1,
        y: 0,
        width: 1,
        height: 1,
      },
      page: 1,
    },
    {
      id: "1.3",
      name: "Finder",
      logo: "/application/Finder.png",
      position: {
        x: 2,
        y: 0,
        width: 1,
        height: 1,
      },
      page: 1,
    },
  ],
  [
    {
      id: "2.1",
      name: "Finder",
      logo: "/application/Finder.png",
      position: {
        x: 0,
        y: 0,
        width: 1,
        height: 1,
      },
      page: 1,
    },
    {
      id: "2.2",
      name: "Finder",
      logo: "/application/Finder.png",
      position: {
        x: 1,
        y: 0,
        width: 1,
        height: 1,
      },
      page: 1,
    },
    {
      id: "2.3",
      name: "Finder",
      logo: "/application/Finder.png",
      position: {
        x: 2,
        y: 0,
        width: 1,
        height: 1,
      },
      page: 1,
    },
  ],
];

export const DOCK_DAPP = [
  {
    id: "D.1",
    name: "Finder",
    logo: "/application/Finder.png",
    position: {
      x: 0,
      y: 0,
      width: 1,
      height: 1,
    },
    isFavorite: true,
    page: 1,
  },
  {
    id: "D.2",
    name: "Launchpad",
    logo: "/application/Launchpad.png",
    position: {
      x: 1,
      y: 0,
      width: 1,
      height: 1,
    },
    isFavorite: true,
    page: 1,
  },
  {
    id: "D.3",
    name: "Safari",
    logo: "/application/Safari.png",
    position: {
      x: 2,
      y: 0,
      width: 1,
      height: 1,
    },
    isFavorite: true,
    page: 1,
  },
  {
    id: "D.3.1",
    name: "App Store",
    logo: "/application/app_store.png",
    position: {
      x: 2,
      y: 0,
      width: 1,
      height: 1,
    },
    isFavorite: true,
    page: 1,
  },
  {
    id: "D.4",
    name: "System Settings",
    logo: "/application/Settings.png",
    position: {
      x: 3,
      y: 0,
      width: 1,
      height: 1,
    },
    isFavorite: true,
    page: 1,
  },
  {
    id: "D.5",
    name: "Terminal",
    logo: "/application/Terminal.png",
    position: {
      x: 4,
      y: 0,
      width: 1,
      height: 1,
    },
    isFavorite: true,
    page: 1,
  },
  {
    id: "D.6",
    name: "TV",
    logo: "/application/TV.png",
    position: {
      x: 5,
      y: 0,
      width: 1,
      height: 1,
    },
    isFavorite: true,
    page: 1,
  },
  {
    id: "D.7",
    name: "Calendar",
    logo: "/application/Calendar.png",
    position: {
      x: 5,
      y: 0,
      width: 1,
      height: 1,
    },
    isFavorite: true,
    page: 1,
  },
  {
    id: "D.8",
    name: "Photos",
    logo: "/application/Photos.png",
    position: {
      x: 5,
      y: 0,
      width: 1,
      height: 1,
    },
    isFavorite: true,
    page: 1,
  },
  {
    id: "D.9",
    name: "Trash",
    logo: "/application/trash_empty.png",
    position: {
      x: 5,
      y: 0,
      width: 1,
      height: 1,
    },
    isFavorite: true,
    page: 1,
  },
];
